### ISSUE TITLE
Refactoring LUIS technology entity

### ISSUE THREAD

**Issue by kevinleung23** [gcrev93/HannahHackathon#3]
Suggested approach for the technology entities using list. Since there are so many synonyms for the tech we are offering help, I believe list is the best approach.

@jcocchi 

![image](https://user-images.githubusercontent.com/17578180/30987001-0f389b66-a45b-11e7-87eb-2ee9c6267c81.png)

**Comment by jcocchi** [comment]
Okay I think that looks good. For cognitive services, we might want to add specific API names to the list like "face api" and "speech api" 

We could go on forever listing different tech we can help with so we need to pick and choose what's important, but I think this is a good list so far. We should at least cover each tech from our techhelp dialog and add others as we see fit (like javascript, C#, etc.)

**Comment by kevinleung23** [comment]
I agree. The new model is created with these this entity as a List, feel free to add on!
